In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris, make_classification
from sklearn.utils import check_random_state
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict

In [46]:
X,y = load_iris(return_X_y=True)
X,y = make_classification(n_samples=20000,n_classes=3,n_informative=7,weights=[.2,.5,.3])
X,yn = noisify(X,y,.15,None)

In [47]:
y_yn = confusion_matrix(y,yn)
y_yn_n = normalize(y_yn,norm='l1',axis=1)
print(y_yn,'\n\n',y_yn_n)

[[3396  317  310]
 [ 728 8525  712]
 [ 454  479 5079]] 

 [[0.84414616 0.07879692 0.07705692]
 [0.07305569 0.85549423 0.07145008]
 [0.07551564 0.07967399 0.84481038]]


In [48]:
X,yp = noisify(X,y,.07,None) #cross_val_predict(GaussianNB(),X,y,cv=5)
y_yp = confusion_matrix(y,yp)
y_yp_n = normalize(y_yp,norm='l1',axis=1)
print(y_yp,'\n\n',y_yp_n)

[[3741  128  154]
 [ 361 9246  358]
 [ 204  195 5613]] 

 [[0.92990306 0.03181705 0.03827989]
 [0.03622679 0.92784747 0.03592574]
 [0.03393214 0.03243513 0.93363273]]


In [49]:
yn_yp = confusion_matrix(yn,yp)
yn_yp_n = normalize(yn_yp,norm='l1',axis=1)
print(yn_yp,'\n\n',yn_yp_n)

[[3191  806  581]
 [ 624 7927  770]
 [ 491  836 4774]] 

 [[0.69702927 0.17605941 0.12691131]
 [0.06694561 0.85044523 0.08260916]
 [0.08047861 0.13702672 0.78249467]]


In [50]:
y_yn_n.T @ y_yp_n

array([[0.79018308, 0.09709214, 0.10544227],
       [0.10696882, 0.79885948, 0.10813684],
       [0.1029101 , 0.09614803, 0.79425925]])

In [51]:
y_yn_n @ y_yp_n.T

array([[0.79043091, 0.10646056, 0.10314234],
       [0.09788912, 0.79898162, 0.09693513],
       [0.10509646, 0.10701143, 0.79388927]])

In [52]:
yn_yp @ np.ones_like(yn_yp_n[:,0]),np.bincount(yn),np.bincount(yn)/len(yn)

(array([4578., 9321., 6101.]),
 array([4578, 9321, 6101], dtype=int32),
 array([0.2289 , 0.46605, 0.30505]))

In [53]:
np.bincount(y),np.bincount(y)/len(y)

(array([4023, 9965, 6012], dtype=int32), array([0.20115, 0.49825, 0.3006 ]))

In [54]:
yr = np.linalg.inv(y_yn_n) @ yn_yp @ np.ones_like(yn_yp_n[:,0])
yk = yr.astype('int')
yk/len(y)

array([0.19715, 0.5032 , 0.296  ])

array([0.2035, 0.5115, 0.278 ])